import Head from "next/head";
import { PlayerList } from "../../components/PlayerList";
import { Rules } from "../../components/Rules";
import { Divider } from "../../components/Divider";
import { useContext, useEffect, useState } from "react";
import { UserService } from "../../services/userService";
import { AppContext } from "../../context/app.context";

export default function Home() {
  const { setPlayers } = useContext(AppContext);

  useEffect(() => {
    UserService.getPlayers().then((data) => {
      setPlayers?.(data ?? []);
    });
  }, []);

  return (
    <>
      <Head>
        <title>RPSLS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Divider />
      <PlayerList />
      <Divider />
      <Rules />
    </>
  );
}
